# Generated by Django 4.2.2 on 2023-07-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
